apiVersion: v1
kind: Service
metadata:
  name: k8s-starter-svc
  labels:
    app: k8s-starter-svc
spec:
  selector:
    app: k8s-starter
  ports:
    - port: 8002
      name: k8s-starter-app
      protocol: TCP
      targetPort: 8002
      nodePort: 30001
    - port: 3000
      name: k8s-starter-ui
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
  type: NodePort
